config:
  target: "https://kwqnze338k.us-east-1.awsapprunner.com"
  environments:
    200-VU-load-test:
      phases:
        - duration: 60
          arrivalRate: 5
          name: Warm up
        - duration: 60
          arrivalRate: 5
          rampTo: 50
          name: Ramp up 1
        - duration: 60
          arrivalRate: 50
          rampTo: 100
          name: Ramp up 2
        - duration: 60
          arrivalRate: 100
          rampTo: 150
          name: Ramp up 3
        - duration: 60
          arrivalRate: 150
          rampTo: 200
          name: Ramp up 4
        - duration: 300
          arrivalRate: 200
          name: Sustained Load
