config:
  target: "https://kwqnze338k.us-east-1.awsapprunner.com"
  environments:
    200-VU-load-test:
      phases:
        - duration: 60
          arrivalRate: 5
          maxVusers: 10
          name: Warm up
        - duration: 720
          arrivalRate: 5
          rampTo: 100
          maxVusers: 200
          name: Ramp up
        - duration: 240
          arrivalRate: 200
          maxVusers: 200
          name: Sustained Load
    400-VU-load-test:
      phases:
        - duration: 60
          arrivalRate: 10
          maxVusers: 10
          name: Warm up
        - duration: 720
          arrivalRate: 10
          rampTo: 200
          maxVusers: 400
          name: Ramp up
        - duration: 240
          arrivalRate: 400
          maxVusers: 400
          name: Sustained Load
