# Stress Test
# multiple enviroments for testing different concurrent user values

config:
  target: "https://kwqnze338k.us-east-1.awsapprunner.com"
  environments:
    625-concurrent-user-stress-test:
      phases:
        - duration: 30
          arrivalRate: 1
          maxVusers: 5
          name: Warm up

        - duration: 60
          arrivalRate: 5
          maxVusers: 50
          name: 1. Ramp Up

        - duration: 60
          arrivalRate: 25
          maxVusers: 250
          name: 2. Ramp Up

        - duration: 60
          arrivalRate: 125
          maxVusers: 450
          name: 3. Ramp Up

        - duration: 60
          arrivalRate: 375
          maxVusers: 600
          name: 4. Ramp Up

        - duration: 240
          arrivalRate: 625
          maxVusers: 625
          name: Hold Load

    1250-concurrent-user-stress-test:
      phases:
        - duration: 30
          arrivalRate: 1
          maxVusers: 5
          name: Warm up

        - duration: 60
          arrivalRate: 50
          maxVusers: 100
          name: 1. Ramp Up

        - duration: 60
          arrivalRate: 100
          maxVusers: 250
          name: 2. Ramp Up

        - duration: 60
          arrivalRate: 200
          maxVusers: 500
          name: 3. Ramp Up

        - duration: 60
          arrivalRate: 400
          maxVusers: 750
          name: 4. Ramp Up

        - duration: 60
          arrivalRate: 800
          maxVusers: 1000
          name: 5. Ramp Up

        - duration: 240
          arrivalRate: 1250
          maxVusers: 1250
          name: Hold Load
