# Stress Test
# multiple enviroments for testing different concurrent user values
# 10 Workers in each environment

# 9000 concurrent user
# 12000 concurrent user

config:
  target: "https://kwqnze338k.us-east-1.awsapprunner.com"
  environments:
    300-concurrent-user-stress-test:
      phases:
        - duration: 30
          arrivalRate: 1
          maxVusers: 5
          name: Warm up

        - duration: 60
          arrivalRate: 60
          maxVusers: 60
          name: 1. Ramp Up

        - duration: 60
          arrivalRate: 120
          maxVusers: 120
          name: 2. Ramp Up

        - duration: 60
          arrivalRate: 180
          maxVusers: 180
          name: 3. Ramp Up

        - duration: 60
          arrivalRate: 240
          maxVusers: 240
          name: 4. Ramp Up

        - duration: 240
          arrivalRate: 300
          maxVusers: 300
          name: Hold Load

    600-concurrent-user-stress-test:
      phases:
        - duration: 30
          arrivalRate: 1
          maxVusers: 5
          name: Warm up

        - duration: 60
          arrivalRate: 60
          maxVusers: 60
          name: 1. Ramp Up

        - duration: 60
          arrivalRate: 120
          maxVusers: 120
          name: 2. Ramp Up

        - duration: 60
          arrivalRate: 180
          maxVusers: 180
          name: 3. Ramp Up

        - duration: 60
          arrivalRate: 240
          maxVusers: 240
          name: 4. Ramp Up

        - duration: 60
          arrivalRate: 300
          maxVusers: 300
          name: 5. Ramp Up

        - duration: 60
          arrivalRate: 360
          maxVusers: 360
          name: 6. Ramp Up

        - duration: 60
          arrivalRate: 420
          maxVusers: 420
          name: 7. Ramp Up

        - duration: 60
          arrivalRate: 480
          maxVusers: 480
          name: 8. Ramp Up

        - duration: 60
          arrivalRate: 540
          maxVusers: 540
          name: 9. Ramp Up

        - duration: 240
          arrivalRate: 600
          maxVusers: 600
          name: Hold Load
